### ISSUE TITLE
ETH Price

### ISSUE THREAD

**Issue by yazeed** [kodycode/CoinMarketDiscordBot#41] opened 2018-02-06 23:42 UTC
Hello, hope you're doing great in the crypto market, and thanks for your updates so far. I wish I could help develop this with you.

Do you think it would it be possible to look at the ETH price of tokens since for tokens that's what we mostly get used to looking at?

**Comment by kodycode** [comment] 2018-02-07 03:47
No worries, hearing out more ideas for the bot is enough help in developing the bot for me.

ETH prices sound like a sure thing I can add, however things have been pretty busy on my end and ETH prices aren't supported by the coinmarketcap API so I'll have to pick this up at a later time where I can sit down and dive in on this.

I'll come back with an update when I get it going.

**Comment by kodycode** [comment] 2018-02-16 00:16
I was finally able to find time to get this feature in. Although ETH-based tokens would generally have the price in ETH, the coinmarketcap API doesn't really provide a way to tell me that something is a token so I've made the ETH price display regardless of what cryptocurrency it is.

**Comment by yazeed** [comment] 2018-02-16 10:06
Thanks for the update mate, though, the price is showing as Price (ETH): 0.50520078 for all cryptocurrencies.

**Comment by kodycode** [comment] 2018-02-16 13:15
Whoah that’s not right,

<s>Weird it was working as intended earlier but I guess there’s been a hiccup.</s> I’ll come back to fix this later today.

EDIT: Guess the lack of sleep is getting to me because it clearly wasn't working from the beginning.

**Comment by kodycode** [comment] 2018-02-16 14:09
Should be fixed now as of https://github.com/kodycode/CoinMarketBot/commit/97783bfb83e2696422ad7fae95afad1a92721a7c. I just need to get home to update the bot.

**Closed as completed** 2018-02-16 20:54 UTC
Labels: enhancement
